### PR TITLE
[FIX] Remove multiprocessing module usage to start tests, linearize tests' start

### PR DESCRIPTION
**Pull request by Tarun-Arora**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that another pull request for this purpose does not exist.
- [ ] I have considered, and confirmed that this submission will be valuable to others.
- [ ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ ] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

This PR is to fix errors when there are both linux and windows tests and we get a SSL error due to the multiprocessing module
Error:
image

### CODE REVIEW

**Comment by Tarun-Arora** [comment]
This prevents the running of tests as the corn job itself couldn't start
If this takes time, we can also consider removing the multiprocessing module as starting a test and creating a GCP instance doesn't take too much time than compared to KVM instance...

**Comment by canihavesomecoffee** [comment]
Can you explain why this is fixing it? IIRC the default setting for multiprocessing is already "fork"

**Comment by Tarun-Arora** [comment]
I am yet to verify if this change successfully solves the issue on spdev.ccextractor.org

**Comment by Tarun-Arora** [comment]
> Can you explain why this is fixing it? IIRC the default setting for multiprocessing is already "fork"

Oh I just checked, it is 'fork' for POSIX systems, I thought it was 'spawn' but that is for windows systems

**Review by thealphadollar — APPROVED** [review]
LGTM.

**Pull request merged**
