### PR TITLE
[Improvement] Add Instructions For Local Testing

### PR DESCRIPTION
**Pull request by thealphadollar**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [X] I am an active contributor to the project.

---

The PR provides following improvements:
- Add testing dependencies to Pipfile and requirements.txt
- Add instructions for running tests locally
- Recommend users to run tests before submitting PR

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
```
 Could not find a version that satisfies the requirement nosetests (from -r requirements.txt (line 18)) (from versions: )
No matching distribution found for nosetests (from -r requirements.txt (line 18))
The command "pip install -r requirements.txt" failed and exited with 1 during .
```

**Comment by thealphadollar** [comment]
@canihavesomecoffee Fixed.

**Comment by canihavesomecoffee** [comment]
codecov shouldn't be in the requirements, as it's a dev/testing dependency.

**Comment by thealphadollar** [comment]
> codecov shouldn't be in the requirements, as it's a dev/testing dependency.

Yeah, I thought the same but didn' apply. I've removed it from the requirements.txt now and have just kept it in pipenv since it can distinguish between dev and non-dev dependencies.

**Pull request merged**
