### PR TITLE
[IMPROVEMENT] Prevent running tests until and unless Github Actions succeeds

### PR DESCRIPTION
**Pull request by devmrfitz**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Prevent running tests until and unless Github Actions succeeds

### CODE REVIEW

**Comment by devmrfitz** [comment]
When actions fail: https://github.com/devmrfitz/ccextractor/commit/697c90c05131fd073cbaeb24bcc4436da550c631
When actions succeed: https://github.com/devmrfitz/ccextractor/commit/95fe23d83a58ccca2844fc073fc2fba18f26e616

**Review by thealphadollar — APPROVED** [review]
Thanks for the PR, @devmrfitz

**Comment by devmrfitz** [comment]
- https://github.com/devmrfitz/ccextractor/commit/2247850fc896412e7eba5b6f6e9a4973570b041e
- https://github.com/devmrfitz/ccextractor/commit/5625c51e9ac2316fd05c31f6b43fa796ebe7cddc
- https://github.com/devmrfitz/ccextractor/commit/d5266cb6aa0dc13373ef79e31c2ceae3bec42800
- https://github.com/devmrfitz/ccextractor/commit/512bd1a8f6116d40cc046a1304a597d8e4560adf

**Comment by thealphadollar** [comment]
Any progress on this? is this ready for review?

**Comment by devmrfitz** [comment]
@

> Any progress on this? is this ready for review?

@thealphadollar This PR is ready for handling pushes/merges. Some minor changes need to be done for handling PRs. It was discussed with @canihavesomecoffee that I'll continue work on this in the GSoC pre-coding period

**Comment by thealphadollar** [comment]
@devmrfitz is there any update on the PR?

**Comment by devmrfitz** [comment]
@thealphadollar I'm a bit tied up at the moment. Will try to finalise this as soon as I have time

**Pull request closed without merging**
