### PR TITLE
 [IMPROVEMENT] Added database migration using flask migrate 

### PR DESCRIPTION
**Pull request by T1duS**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
(It exists but this one uses a better method)
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [X] I am an active contributor to the project.

---
I added database migration using alembic here --
https://github.com/CCExtractor/sample-platform/pull/253/

In this PR, I have added database migration using flask-migrate since it is easier to use than alembic.

Steps to do migration --
1. python3 manage.py db init (You only need to do this once)
2. python3 manage.py db migrate
3. python3 manage.py db upgrade

### CODE REVIEW

**Comment by thealphadollar** [comment]
@T1duS @canihavesomecoffee Please look intot this forgotten gem :stuck_out_tongue:

**Comment by aadibajpai** [comment]
@pep8speaks suggest diff

**Comment by aadibajpai** [comment]
@canihavesomecoffee it works :tada:

**Comment by thealphadollar** [comment]
@aadibajpai Please do a rebase of the master branch on this branch.

**Pull request closed without merging**
