### PR TITLE
[IMPROVEMENT] Drop support for python3.7, upgrade to latest python versions

### PR DESCRIPTION
**Pull request by Tarun-Arora**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

---

This PR implements migration of the platform from older versions of python to new versions - 3.10. 3.11, 3.12.0a2

Implementation Breakup- 
- [x] Replace `githubpy` as it is no longer being maintained
- [x] Replace `nose` as it is no longer being maintained
- [x] Update tests as per the latest implementation
- [x] Update GitHub workflows
- [ ] E2e testing

Implements #757 

Thanks to @MatejMecka , for the idea of using PyGithub (replacing githubpy)

### CODE REVIEW

**Comment by Tarun-Arora** [comment]
Hey @thealphadollar, thanks for the suggestion for migrating to `nose2` from the previously deprecated `nose`. The changes have been made. I would like to bring to your notice the following:
1. The repo owners have marked the builds of python 3.7 and 3.8 as required, but as per the issue, it says python 3.7 is being deprecated, so please update that.
2. I have to fix the failing codecov report and do e2e testing for the platform, so please not merge this now.
3. Since the PR is already big, I can help you with reviewing this.

**Comment by canihavesomecoffee** [comment]
@Tarun-Arora It'd be better to split this up then:

- 1 PR to upgrade the CI (and gitignore), that should be easy to get merged
- 1 (or more PR's) that update different components.

**Comment by Tarun-Arora** [comment]
> @Tarun-Arora It'd be better to split this up then:
> 
> * 1 PR to upgrade the CI (and gitignore), that should be easy to get merged
> * 1 (or more PR's) that update different components.

Cool, I'll split the PR

**Comment by thealphadollar** [comment]
@Tarun-Arora Any updates on the second PR including changes related to maintenance packages?

**Comment by Tarun-Arora** [comment]
> @Tarun-Arora Any updates on the second PR including changes related to maintenance packages?

Yes the upcoming next PR would be for migrating from githubpy to PyGithub, I have made the changes, just testing e2e
Would raise the PR by tomorrow.

**Pull request closed without merging**
