### PR TITLE
[FIX] Fix incorrect PR comment generation

### PR DESCRIPTION
**Pull request by pranavrajpal**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

---

Fixes (part of) #535 (see below for more info)

This fixes a bug in the generation of the PR comment that caused it to mark regression tests as failing if they produced one of the allowed variants of the expected output file, instead of correctly marking these tests as passing. I also added a few tests for this bug.

I don't think this is a complete fix for #535 because I don't think it completely accounts for the difference between https://github.com/CCExtractor/ccextractor/pull/1329#issuecomment-827744099 and https://sampleplatform.ccextractor.org/test/3224. In that comment, the table and the list of failed tests show different results, but the changes I made and the bug I found affect the results for both the table and the list of failed tests in the same way.

Judging from the template for the PR comment, that would probably be caused by `tests` and `failed_tests` in the template getting out of sync, but I can't tell what the cause of that might be just from looking at the code. I also don't know how to debug that problem because I can't tell what regression tests were incorrectly marked as failing.

### CODE REVIEW

**Comment by pranavrajpal** [comment]
I don't think the CI failing is related to this PR, seeing as `sudo apt-get install libvirt-dev` seems to be getting a 404 when trying to install those packages.

From what I can tell, this appears to be related to actions/virtual-environments#2104 and there seems to be a relatively simple solution in https://github.com/actions/virtual-environments/issues/2104#issuecomment-731375911. I'll send a PR with that fix.

**Comment by canihavesomecoffee** [comment]
@pranavrajpal can you take a look at the CI? Some tests fail.

**Comment by pranavrajpal** [comment]
I created #543 to fix that bug and one other related bug I found while fixing it, but, for reasons I don't understand, the CI seems to be failing when trying to generate the coverage report. Could you take a look and see if you know what's going wrong?

**Comment by pranavrajpal** [comment]
The CI appears to be passing now. Is there anything else you want me to change/fix?

**Comment by kvshravan** [comment]
Nice work 👍 Can you move the data classes to models.py and then import them as required?

**Comment by pranavrajpal** [comment]
I've moved the data classes to models.py.

I'm slightly confused on how you decide what goes in controllers.py and what goes in models.py. I originally thought models.py was meant for database models and controllers.py was for everything else. Is models.py meant for any classes for storing data, and controllers.py for the rest of the actual logic, or is there some other distinction between what goes in each file?

**Comment by kvshravan** [comment]
I think you can go through mod_sample, afaik Mediainfoparser.py contains custom classes. It's not much of a deal, it's better if the classes aren't defined in controllers.py. @canihavesomecoffee has a say on this

**Comment by pranavrajpal** [comment]
Ok, keeping all of the classes out of controllers.py so that all of the actual logic is kept together makes sense.

The data classes are in models.py and the CI seems to be passing, so let me know if you want me to change anything else.

**Comment by kvshravan** [comment]
LGTM.

**Comment by canihavesomecoffee** [comment]
In general the models were for database (ORM) purposes, but I'd rather see the classes under model than tacked to the controller file. The controller file should be reserved for logic wrt handling requests :)

**Review by canihavesomecoffee — APPROVED** [review]

**Pull request merged**
