### PR TITLE
[IMPROVEMENT] Add checks for draft PR in webhook requests

### PR DESCRIPTION
**Pull request by Tarun-Arora**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively but have not contributed previously.
- [x] I am an active contributor to the project.

---

This PR is just the completion of #775, with unit tests and canceling of current tests when PR is marked as a draft.

### CODE REVIEW

**Review by canihavesomecoffee — CHANGES_REQUESTED** [review]
I'd expect a test with a draft PR and one where there's no more draft (the existing ones).

**Comment by canihavesomecoffee** [comment]
@Tarun-Arora can you check if there's any non-overlapping changes with #775 and reduce the PR to these only? That way we can still merge this; if there's no unique changes in here we can close it :)

**Comment by Tarun-Arora** [comment]
> @Tarun-Arora can you check if there's any non-overlapping changes with #775 and reduce the PR to these only? That way we can still merge this; if there's no unique changes in here we can close it :)

Sure, did the changes, ready for review now.

**Review by thealphadollar — APPROVED** [review]
LGTM! Thanks for the PR, Tarun.

**Pull request merged**
