### PR TITLE
Add downloading regression output files

### LINKED ISSUE #289: [PROPOSAL] Make Output Files Available
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

The expected output for the sample is currently stored on the server and can be easily exposed at an endpoint as we already serve samples, sample info, and additional information under `mod_sample/controllers.py`.

The file path for the expected test results can be fetched using the following function present in the model for regression test. This fetched filename needs to be combined with `os.path.join(config.get('SAMPLE_REPOSITORY', ''), 'TestResults')` to get full file path for providing download.

### PR DESCRIPTION
**Pull request by thealphadollar**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

---

- Provide a method to download Regression test output file given RTO id.
- Change the view to show available files to download.

As per the [NGINX X-Accel Docs](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) a new folder needs to be made as per [line 213](https://github.com/CCExtractor/sample-platform/blob/a90240df39df370c12a313be2179dff1c2f57f83/mod_regression/controllers.py#L213) which states that we provide the download file from a different folder than actually we are referring to.

NOTE: This has not been tested on a running server.

fixes #289 

Apologies for the misleading branch name.

### CODE REVIEW

**Comment by thealphadollar** [comment]
The CI passing of this depends on #314

**Comment by canihavesomecoffee** [comment]
You also might want to update the default nginx config that we use upon installation.

**Comment by thealphadollar** [comment]
> No tests added for this?

I was waiting for tests to see what functions aren't checked and then write tests.

**Comment by thealphadollar** [comment]
@canihavesomecoffee PR updated.

**Pull request merged**
